[tool.poetry]
name = "aurflux"
version = "1.2.75"
description = "Aurflux!"
authors = ["Zenith <inbox@zenith.dev>"]

[tool.poetry.dependencies]
python = "^3.9"
"discord.py" = "*"
aurcore = "*"
pyyaml = "*"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
