[tool.poetry]
name = "mf88-affilitest"
version = "0.1.1"
description = ""
authors = ["vutr <me@vutr.io>"]

[tool.poetry.dependencies]
python = "^3.7.5"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
