[tool.poetry]
name = "paten"
version = "0.1.0"
description = ""
authors = ["yoshiki <yoshiki0911@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
jupyterlab = "^2.1.3"
wheel = "^0.35.1"
twine = "^3.2.0"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
