[tool.poetry]
name = "eventz"
version = "0.3.0"
description = "Eventz: an event-centric microframework."
authors = ["Dan Ballance <work@danballance.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
immutables = "^0.14"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
