[tool.poetry]
name = "skinner"
version = "0.2.1"
description = ""
authors = ["William Song <30965609+Freakwill@users.noreply.github.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/Freakwill/skinner"
repository = "https://github.com/Freakwill/skinner"
keywords = ["gym", "Reinforcement Learning", "Artificial Intelligence"]
classifiers = [
    "Environment :: MacOS X",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Science/Research",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
